# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build & Test

on:
  pull_request:
    branches: [ "main" ]

env:
  GOPRIVATE: github.com/andrei-cosmin/sandata

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Add SSH Go Module Private Key
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        echo $GOPRIVATE
        mkdir -p ~/.ssh
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        ssh-agent -a $SSH_AUTH_SOCK > /dev/null	
        ssh-add - <<< "${{ secrets.GO_MODULE_PRIVATE_KEY }}"
        echo "SSH_AUTH_SOCK=$SSH_AUTH_SOCK" >> $GITHUB_ENV  
    - name: Setup access for private go modules
      run: |
         git config --global url."ssh://git@github.com/".insteadOf https://github.com/
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
